# Generated by Django 6.0 on 2025-12-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depoimento',
            name='avaliação',
            field=models.PositiveIntegerField(default=5, verbose_name='avaliação (1-5)'),
        ),
    ]
