# Generated by Django 6.0 on 2025-12-26 16:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_depoimento_avaliação'),
    ]

    operations = [
        migrations.AddField(
            model_name='depoimento',
            name='cliente_desde',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='cliente desde'),
            preserve_default=False,
        ),
    ]
