# Generated by Django 6.0 on 2025-12-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_depoimento_cliente_desde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depoimento',
            name='avaliação',
            field=models.PositiveIntegerField(choices=[('star', 'Star')], default='star', help_text='Número de estrelas (1 a 5)', max_length=5, verbose_name='avaliação (1-5)'),
        ),
    ]
