# Generated by Django 6.0 on 2025-12-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_depoimento_avaliação'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depoimento',
            name='avaliação',
        ),
        migrations.AddField(
            model_name='depoimento',
            name='avaliacao',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, help_text='Número de estrelas (1 a 5)', verbose_name='Avaliação (1-5)'),
        ),
        migrations.AlterField(
            model_name='depoimento',
            name='cliente_desde',
            field=models.DateField(auto_now_add=True, verbose_name='Cliente desde'),
        ),
        migrations.AlterField(
            model_name='depoimento',
            name='comentario',
            field=models.TextField(max_length=500, verbose_name='Comentário'),
        ),
        migrations.AlterField(
            model_name='depoimento',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do cliente'),
        ),
    ]
