# Generated by Django 6.0 on 2025-12-26 17:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_depoimento_avaliação_depoimento_avaliacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depoimento',
            name='avaliacao',
        ),
        migrations.RemoveField(
            model_name='depoimento',
            name='cliente_desde',
        ),
        migrations.AddField(
            model_name='depoimento',
            name='inicio',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='data de início'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='depoimento',
            name='comentario',
            field=models.TextField(max_length=500, verbose_name='comentário'),
        ),
        migrations.AlterField(
            model_name='depoimento',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='nome do cliente'),
        ),
    ]
