# Generated by Django 6.0 on 2026-04-11 08:31

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_depoimento_cliente_desde'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrossel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='criaçao')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='atualizado')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('titulo', models.CharField(max_length=100, verbose_name='titulo')),
                ('descricao', models.TextField(max_length=500, verbose_name='descrição')),
                ('foto', stdimage.models.StdImageField(force_min_size=False, upload_to='carrossel', variations={'thumb': (800, 600)}, verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Carrossel',
                'verbose_name_plural': 'Carrosseis',
            },
        ),
    ]
